name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve the issue.

  - type: dropdown
    id: sdk
    attributes:
      label: Which SDK are you using?
      options:
        - TypeScript/JavaScript
        - Python
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SDK Version
      description: What version of TealTiger are you using?
      placeholder: "e.g., 0.2.2"
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider are you using?
      options:
        - OpenAI
        - Anthropic
        - Azure OpenAI
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { TealOpenAI } from 'tealtiger';
        
        const client = new TealOpenAI({
          apiKey: process.env.OPENAI_API_KEY,
        });

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      value: |
        - OS: [e.g., macOS 13.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g., 18.16.0]
        - Python version: [e.g., 3.11.0]
        - Package manager: [e.g., npm, yarn, pip]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
