name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - README
        - API Reference
        - Code Examples
        - Tutorial/Guide
        - Installation Instructions
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue? (URL or file path)
      placeholder: "https://github.com/agentguard-ai/tealtiger/blob/main/README.md"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - Incorrect information
        - Missing information
        - Unclear/confusing
        - Typo/grammar
        - Broken link
        - Outdated content
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: "The documentation says... but it should say..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix this, please describe it
      placeholder: "I suggest changing the text to..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the documentation issue
