name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: dropdown
    id: sdk
    attributes:
      label: Which SDK is this for?
      options:
        - TypeScript/JavaScript
        - Python
        - Both
        - Core Platform
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New Guardrail
        - Cost Tracking Enhancement
        - New AI Provider Support
        - API Enhancement
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: "In my application, I need to..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: If applicable, provide an example of how you'd like to use this feature
      render: typescript
      placeholder: |
        const client = new TealOpenAI({
          apiKey: process.env.OPENAI_API_KEY,
          // Your proposed feature here
        });

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to contribute this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I need help implementing this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
